apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zib6sgrc9-nodejs
  janus-idp.io/tekton: zib6sgrc9-nodejs
  backstage.io/kubernetes-id: zib6sgrc9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zib6sgrc9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
